---
dist: bionic
language: python
python:
  - 3.6
virtualenv:
  system_site_packages: true
cache:
  apt: true
  pip: true
addons:
  apt:
    packages:
      - build-essential
      - ffmpeg
      - gifsicle
      - libass-dev
      - libgnutls28-dev
      - libimage-exiftool-perl
      - libjpeg-dev
      - libjpeg-progs
      - liblcms2-dev
      - libpng-dev
      - libssl-dev
      - libvpx-dev
      - libwebp-dev
      - libx264-dev
      - python3-numpy
      - python3-opencv
      - python3-pycurl
      - python3-pyexiv2
      - scons
      - webp

install:
  - pip install -U pip wheel
  - pip install -r test-requirements.txt
  - pip install -e .
script:
  - pylint thumbor_icc
  - pyflakes thumbor_icc
